language: ruby
cache: bundler
rvm:
- 2.1.4
before_install: gem install bundler -v 1.11.2
env:
  global:
    secure: v+L+DSrkYP+C1aXXd3rdH6gBQ+8YRI9c61OujvRJ9JHZrxS+hgjg3rG5TbZNkLXv4whXF2mWNTio0Z6350hxD8bSdDJqjP3M8WrrZDrGN2lPBK//5iKyL6gKipvhsR1heUgCXJBCI7mgYGivOt+df/oa1soT8kvoPILQ4tavA93nk/AQ5QO9bCXrcJR6cY7UQhBTz1DK3Fy57IIjnEW2HWfMla0SYNQNYX+vazxDHEQtcwoXVXHf3pf+wbnIEBkSpNTUSwrAjSyCClYUEFQPWc/dNvHBYuDeiILBuGG18BmKj2P9U/9M4Af++X5mr8h+o++WA8HFNh/PP0+mLk6fGSJ1echWrOdL6S8Fb0UgNSRfuhVx02LpZOf43nwmFb1c2RWSuGVvsW/Qz3bJjtEIbUFXLiIXnwXyYy1Y5Fi+59xXuhOLJ01bwPoRrrEm/RI7dcXdICzm3Jdtll0vIT+zZvP8utN6TNz7a/J1jNNjvr0E+c/TKVZm/y7Vvd67KG9iim9DP+d19QXvA+b0KbAXBJUM6X82JdKH21bMsawBY+IvMP/MLNeSbJZdU8PVmxogdnDbtGCl9zSCzwX4PNgDLxHTLSCuXMMV99MibjlPTKU7DDuH0AEn7knjeQf+GjhaYRt5qSp5HQZrWiHb+nWPtPV9LO78L+4Wp5HGotACj4E=
